/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as PrivateImport } from './routes/_private'

// Create Virtual Routes

const PublicIndexLazyImport = createFileRoute('/_public/')()
const PublicSignupLazyImport = createFileRoute('/_public/signup')()
const PublicSigninLazyImport = createFileRoute('/_public/signin')()
const PrivateAboutLazyImport = createFileRoute('/_private/about')()

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexLazyRoute = PublicIndexLazyImport.update({
  path: '/',
  getParentRoute: () => PublicRoute,
} as any).lazy(() => import('./routes/_public/index.lazy').then((d) => d.Route))

const PublicSignupLazyRoute = PublicSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any).lazy(() =>
  import('./routes/_public/signup.lazy').then((d) => d.Route),
)

const PublicSigninLazyRoute = PublicSigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any).lazy(() =>
  import('./routes/_public/signin.lazy').then((d) => d.Route),
)

const PrivateAboutLazyRoute = PrivateAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/about.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_private/about': {
      id: '/_private/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PrivateAboutLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninLazyImport
      parentRoute: typeof PublicImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupLazyImport
      parentRoute: typeof PublicImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexLazyImport
      parentRoute: typeof PublicImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  PrivateRoute: PrivateRoute.addChildren({ PrivateAboutLazyRoute }),
  PublicRoute: PublicRoute.addChildren({
    PublicSigninLazyRoute,
    PublicSignupLazyRoute,
    PublicIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/_public"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/about"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/signin",
        "/_public/signup",
        "/_public/"
      ]
    },
    "/_private/about": {
      "filePath": "_private/about.lazy.tsx",
      "parent": "/_private"
    },
    "/_public/signin": {
      "filePath": "_public/signin.lazy.tsx",
      "parent": "/_public"
    },
    "/_public/signup": {
      "filePath": "_public/signup.lazy.tsx",
      "parent": "/_public"
    },
    "/_public/": {
      "filePath": "_public/index.lazy.tsx",
      "parent": "/_public"
    }
  }
}
ROUTE_MANIFEST_END */
